export const CHARACTERS_V17={
  renee:{id:'renee',name:'Renee Ward',role:'Present-day Dispatcher',states:{known:'Your dispatcher outside Pinewood. She is tracing the impossible work order while keeping your radio channel open.',radio_compromised:'Renee is real, but Pinewood can imitate speech carried through its systems. Voice alone is no longer proof.',ally:'Renee is reconstructing the 1997 incident from outside while you verify it physically inside the mall.'}},
  eli:{id:'eli',name:'Eli Mercer',role:'Electrical Contractor',states:{rumor:'An outside electrical contractor disappeared during Pinewood’s 1997 closing incident.',identified:'Eli Mercer entered Pinewood on an emergency call on November 14, 1997 and never received a valid exit event.',body_found:'Eli died inside Pinewood while trying to reach the closing controls. He is not The Attendant.',unresolved:'Eli’s temporary contractor session remained active in PCAS after his death.'}},
  jo:{id:'jo',name:'Jo Alvarez',role:'Closing Manager',states:{known:'Pinewood’s closing manager in 1997. She stopped trusting the automated count and began tracking staff by hand.',survivor:'Jo got employees out during the Last Shift and later challenged Pinewood’s official incident report.',roster:'Jo’s handwritten roster is the most reliable record of who actually left the building.'}},
  luis:{id:'luis',name:'Luis Ortega',role:'Night Security Supervisor',states:{known:'Night Security supervisor during the 1997 incident.',pattern:'Luis discovered that Pinewood’s staff calls preceded The Attendant’s movements.',body_found:'Luis died barricaded in secondary Security after disabling part of the PA chain.'}},
  tessa:{id:'tessa',name:'Tessa Kim',role:'Cassette Castle Closing Clerk',states:{known:'A nineteen-year-old Cassette Castle employee working the Last Shift.',survivor:'Jo got Tessa out through receiving even while PCAS continued calling her name.',importance:'Tessa proves that Pinewood’s accountability record can remain wrong even after someone physically leaves.'}},
  andre:{id:'andre',name:'Andre Bell',role:'Pinewood Maintenance Technician',states:{known:'Pinewood’s senior maintenance technician in 1997.',survivor:'Andre survived the Last Shift with injuries and resigned immediately afterward.',older_story:'Andre’s later statement mentions older employee stories about a man who appeared after closing.'}},
  kessler:{id:'kessler',name:'Martin Kessler',role:'Mall Operations Director',states:{known:'Operations director who championed Pinewood’s automated closing system.',coverup:'Kessler approved manual overrides and inaccurate all-clear records to reopen Pinewood after the 1997 incident.'}},
  gavin:{id:'gavin',name:'Gavin Cole',role:'Property Inspector',states:{identified:'A property inspector who entered the closed mall in 2023 after receiving a Pinewood facilities ticket.',body_found:'Gavin died below grade. His paperwork references CONTRACTOR 13, proving the loop continued after public closure.'}},
  denise:{id:'denise',name:'Denise Park',role:'Video Planet Assistant Manager',states:{known:'Video Planet closer on the 1997 final staff roster.'}},
  marcus:{id:'marcus',name:'Marcus Reed',role:'Food Court Custodian',states:{known:'Food Court closer on the 1997 final staff roster.'}},
  nina:{id:'nina',name:'Nina Flores',role:'Sunburst Arcade Closer',states:{known:'Sunburst Arcade closer on the 1997 final staff roster.'}},
  caleb:{id:'caleb',name:'Caleb Moss',role:'Loading Associate',states:{known:'Loading associate on the 1997 final staff roster.'}}
};
