export const DIALOGUE_V17={
  ch1_start:{id:'ch1_start',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. I have you at Pinewood. Restore emergency circuits A through C, verify the east freight elevator, then clear the property. Keep this channel open.'},
  ch1_first_power:{id:'ch1_first_power',speaker:'RENEE',medium:'radio',text:'Good. One leg is back. I’m also getting activity from a camera that is listed as decommissioned. I’m checking that now.'},
  ch1_pcas_hold:{id:'ch1_pcas_hold',speaker:'PCAS',medium:'intercom',text:'Attention shoppers. Closing has been extended. Employees remain at their stations.'},
  ch1_contractor_registered:{id:'ch1_contractor_registered',speaker:'PCAS',medium:'intercom',text:'Temporary contractor session active. Contractor Fourteen, remain on property until accountability release.'},
  ch1_pcas_route_deviation:{id:'ch1_pcas_route_deviation',speaker:'PCAS',medium:'intercom',text:'Emergency power state updated. Contractor Fourteen, movement outside assigned work area logged.'},
  ch1_second_power:{id:'ch1_second_power',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. Stop a second. I did not give Pinewood your contractor number. That ticket should not be able to register you with anything in the building. Keep moving, but do not follow the PA.'},
  ch1_power_complete:{id:'ch1_power_complete',speaker:'RENEE',medium:'radio',text:'All three circuits are stable. Freight elevator should answer. Get out of there. Do not stop for another announcement.'},
  ch1_key_discrepancy:{id:'ch1_key_discrepancy',speaker:'PCAS',medium:'intercom',text:'Key control discrepancy detected. Temporary contractor Fourteen, return borrowed property to Security.'},
  ch1_key_reaction:{id:'ch1_key_reaction',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. It saw that key come off the hook. Do not answer it. You have what you need. Get to the freight elevator.'},
  ch1_elevator_denied:{id:'ch1_elevator_denied',speaker:'PCAS',medium:'intercom',text:'Contractor Fourteen, departure is not authorized while accountability remains open.'},
  ch1_elevator_reaction:{id:'ch1_elevator_reaction',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. No. Ignore that. The elevator is yours. Get inside and do not wait for another instruction.'},
  ch2_start:{id:'ch2_start',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. I have you below grade. That freight car was not supposed to go down. Find a safe route and give me anything with a panel number or room label.'},
  ch2_1997_ticket:{id:'ch2_1997_ticket',speaker:'RENEE',medium:'radio',text:'I found the original ticket record. I need you to hear me before I say this: it was created November 14, 1997. Same work-order family. Same property. I am not hanging up.'},
  ch3_auth:{id:'ch3_auth',speaker:'RENEE',medium:'radio',text:'Interference is getting worse. Important calls from me start with “Fourteen, Ward on dispatch.” If you hear me giving directions without that, verify before you move.'},
  ch4_fake_route:{id:'ch4_fake_route',speaker:'RENEE?',medium:'radio',text:'Contractor Fourteen, Dispatch. East service corridor is clear. Proceed through Receiving and remain on the marked route.'},
  ch4_real_return:{id:'ch4_real_return',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. Stop. I have not transmitted to you since the stairwell. Whatever just gave you directions was not me.'},
  ch6_accountability_one:{id:'ch6_accountability_one',speaker:'PCAS',medium:'terminal',text:'ACCOUNTABILITY HOLD. STAFF STATUS UNRESOLVED. CONTRACTOR 14 SESSION ACTIVE.'},
  ch6_final_recall:{id:'ch6_final_recall',speaker:'PCAS',medium:'intercom',text:'Contractor Fourteen, return to your assigned station. Closing checklist incomplete.'}
};
