export const DIALOGUE_V17={
  ch1_start:{id:'ch1_start',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. I have you at Pinewood. Restore emergency circuits A through C, verify the east freight elevator, then clear the property. Keep this channel open.'},
  ch1_first_power:{id:'ch1_first_power',speaker:'RENEE',medium:'radio',text:'Good. One leg is back. I’m also getting activity from a camera that is listed as decommissioned. I’m checking that now.'},
  ch1_pcas_hold:{id:'ch1_pcas_hold',speaker:'PCAS',medium:'intercom',text:'Attention shoppers. Closing has been extended. Employees remain at their stations.'},
  ch1_contractor_registered:{id:'ch1_contractor_registered',speaker:'PCAS',medium:'intercom',text:'Temporary contractor session active. Contractor Fourteen, remain on property until accountability release.'},
  ch1_pcas_route_deviation:{id:'ch1_pcas_route_deviation',speaker:'PCAS',medium:'intercom',text:'Emergency power state updated. Contractor Fourteen, movement outside assigned work area logged.'},
  ch1_second_power:{id:'ch1_second_power',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. Stop a second. I did not give Pinewood your contractor number. That ticket should not be able to register you with anything in the building. Keep moving, but do not follow the PA.'},
  ch1_power_complete:{id:'ch1_power_complete',speaker:'RENEE',medium:'radio',text:'All three circuits are stable. Freight elevator should answer. Get out of there. Do not stop for another announcement.'},
  ch1_key_discrepancy:{id:'ch1_key_discrepancy',speaker:'PCAS',medium:'intercom',text:'Key control discrepancy detected. Temporary contractor Fourteen, return borrowed property to Security.'},
  ch1_key_reaction:{id:'ch1_key_reaction',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. It saw that key come off the hook. Do not answer it. You have what you need. Get to the freight elevator.'},
  ch1_elevator_denied:{id:'ch1_elevator_denied',speaker:'PCAS',medium:'intercom',text:'Contractor Fourteen, departure is not authorized while accountability remains open.'},
  ch1_elevator_reaction:{id:'ch1_elevator_reaction',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. No. Ignore that. The elevator is yours. Get inside and do not wait for another instruction.'},

  ch2_start:{id:'ch2_start',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. I have you below grade. That freight car was not supposed to go down. Find a safe route and give me anything with a panel number or room label.'},
  ch2_feeder_found:{id:'ch2_feeder_found',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. That feeder isolation is local. Lock it out before you reset Relay D. I would rather lose thirty seconds than watch you energize a dead branch blind.'},
  ch2_relay_d:{id:'ch2_relay_d',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. Relay D is carrying load. I have the service branch on my side now. Give me a second while I follow the ticket history.'},
  ch2_1997_ticket:{id:'ch2_1997_ticket',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. I found the original ticket record. I need you to hear me before I say this: it was created November 14, 1997. Same work-order family. Same property. I am not hanging up.'},
  ch2_maintenance_eval:{id:'ch2_maintenance_eval',speaker:'PCAS',medium:'intercom',text:'Maintenance staff must report to Security for evaluation.'},
  ch2_pump_ready:{id:'ch2_pump_ready',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. Relay D brought the sump controller back. The east low corridor is flooded. Start the pump and let it clear before you try to cross.'},
  ch2_pump_violation:{id:'ch2_pump_violation',speaker:'PCAS',medium:'intercom',text:'Unauthorized sump cycle detected. Maintenance personnel remain in assigned service zones.'},
  ch2_mask_tutorial:{id:'ch2_mask_tutorial',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. That pump is loud enough to cover your footsteps. Remember it covers anything coming toward you, too.'},
  ch2_route_deviation:{id:'ch2_route_deviation',speaker:'PCAS',medium:'intercom',text:'Temporary contractor Fourteen, maintenance route deviation recorded. Return to assigned service area.'},
  ch2_gavin_body:{id:'ch2_gavin_body',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. I heard you. Stay with me. I am searching the name Gavin Cole now. Do not move his things until I tell you what I find.'},
  ch2_gavin_ticket:{id:'ch2_gavin_ticket',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. Gavin Cole was a property inspector. He disappeared in 2023 after accepting a facilities ticket for Pinewood. The police report says he never came back out.'},
  ch2_contractor13:{id:'ch2_contractor13',speaker:'RENEE',medium:'radio',text:'His ticket says CONTRACTOR 13. Yours says CONTRACTOR 14. Fourteen, this building did not choose that number tonight. You are not the first person it called back.'},
  ch2_relay_e:{id:'ch2_relay_e',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. Relay E is stable. I found two names attached to the 1997 closing file: Jo Alvarez, closing manager, and Luis Ortega, night security. Security is ahead of you. That is where we go next.'},
  ch2_exit:{id:'ch2_exit',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. North service route feeds directly into Security. Go. I am staying on this channel.'},

  ch3_auth:{id:'ch3_auth',speaker:'RENEE',medium:'radio',text:'Interference is getting worse. Important calls from me start with “Fourteen, Ward on dispatch.” If you hear me giving directions without that, verify before you move.'},
  ch4_fake_route:{id:'ch4_fake_route',speaker:'RENEE?',medium:'radio',text:'Contractor Fourteen, Dispatch. East service corridor is clear. Proceed through Receiving and remain on the marked route.'},
  ch4_real_return:{id:'ch4_real_return',speaker:'RENEE',medium:'radio',text:'Fourteen, Ward on dispatch. Stop. I have not transmitted to you since the stairwell. Whatever just gave you directions was not me.'},
  ch6_accountability_one:{id:'ch6_accountability_one',speaker:'PCAS',medium:'terminal',text:'ACCOUNTABILITY HOLD. STAFF STATUS UNRESOLVED. CONTRACTOR 14 SESSION ACTIVE.'},
  ch6_final_recall:{id:'ch6_final_recall',speaker:'PCAS',medium:'intercom',text:'Contractor Fourteen, return to your assigned station. Closing checklist incomplete.'}
};
