export const EVIDENCE_V17={
  'LS-01':{id:'LS-01',title:'Fountain Maintenance Tag',type:'maintenance_tag',chapter:0,requiredForTrueEnding:true,people:['andre'],summary:'Andre Bell physically disconnected the fountain motor before staff reported hearing running water near the dry basin.',timeline:['1997_fountain_disconnected']},
  'LS-02':{id:'LS-02',title:'Dead PA Deck Service Note',type:'service_note',chapter:0,requiredForTrueEnding:true,people:['luis','andre'],summary:'Closing announcements continued after part of Pinewood’s playback chain was disconnected.',timeline:['1997_pa_without_playback']},
  'LS-03':{id:'LS-03',title:'Security Route Sketch',type:'route_sheet',chapter:0,requiredForTrueEnding:true,people:['luis'],summary:'Luis marked that the figure in the halls followed real corridor routes rather than crossing walls.',timeline:['1997_route_pattern']},
  'LS-04':{id:'LS-04',title:'Closing Roster Fragment',type:'roster_fragment',chapter:1,requiredForTrueEnding:true,people:['jo','tessa'],summary:'Jo’s handwritten count disagreed with PCAS after employees physically left Pinewood.',timeline:['1997_accountability_mismatch']},
  'LS-05':{id:'LS-05',title:'Luis Ortega Security VHS',type:'vhs',chapter:2,requiredForTrueEnding:true,people:['luis'],summary:'Security footage shows staff-location pages occurring before The Attendant moves toward the called area.',timeline:['1997_attendant_answers_calls']},
  'LS-06':{id:'LS-06',title:'Tessa Kim — Side B',type:'cassette',chapter:3,requiredForTrueEnding:true,people:['tessa','jo'],summary:'An accidental recording captures Jo getting Tessa outside while Pinewood continues calling Tessa’s name.',timeline:['1997_tessa_exits_unresolved']},
  'LS-07':{id:'LS-07',title:'Final Shift Roster',type:'roster',chapter:4,requiredForTrueEnding:true,people:['jo','eli','luis','tessa','andre','denise','marcus','nina','caleb'],summary:'The reconstructed roster establishes who was truly present, who escaped and which staff records were wrong.',timeline:['1997_roster_reconstructed']},
  'LS-08':{id:'LS-08',title:'Eli Mercer Job Recorder',type:'audio_recorder',chapter:4,requiredForTrueEnding:true,people:['eli'],summary:'Eli learned that killing power only postponed the closing routine and tried to reach PA control before he died.',timeline:['1997_eli_final_route']},
  'LS-09':{id:'LS-09',title:'Management Override Packet',type:'operations_packet',chapter:4,requiredForTrueEnding:true,people:['kessler','eli'],summary:'Pinewood reopened with an unresolved contractor session after management approved inaccurate all-clear records.',timeline:['1997_false_all_clear']},
  'GAVIN-TICKET':{id:'GAVIN-TICKET',title:'Gavin Cole Inspection Ticket',type:'modern_ticket',chapter:1,requiredForTrueEnding:false,people:['gavin'],summary:'A 2023 Pinewood facilities ticket references CONTRACTOR 13.',timeline:['2023_gavin_ticket']},
  'PRE-1986-LOG':{id:'PRE-1986-LOG',title:'1986 Janitorial Log',type:'optional_log',chapter:3,requiredForTrueEnding:false,people:[],summary:'A pre-PCAS log mentions a “night employee” seen after closing.',timeline:['1986_night_employee']}
};

export const LAST_SHIFT_IDS_V17=Object.keys(EVIDENCE_V17).filter(id=>/^LS-\d\d$/.test(id)).sort();
