from pathlib import Path


def one(text, old, new, label):
    n = text.count(old)
    if n != 1:
        raise SystemExit(f'{label}: expected 1 marker, found {n}')
    return text.replace(old, new)


patch_path = Path('patches/chapter6-last-shift-v25.js.txt')
p = patch_path.read_text()

p = one(
    p,
    "  if(type==='ch6_eli_station_v25')return s.eliProcessed?['ELI MERCER • SESSION 01','DECEASED • NO EXIT','CONTRACTOR 01 CLOSED']:['ELI MERCER • SESSION 01','LS-08 + LS-09 REQUIRED','SERVICE STATES FIRST'];\n  return ['CLOSING CONTROL','STATE UNKNOWN'];",
    "  if(type==='ch6_eli_station_v25')return s.eliProcessed?['ELI MERCER • SESSION 01','DECEASED • NO EXIT','CONTRACTOR 01 CLOSED']:['ELI MERCER • SESSION 01','LS-08 + LS-09 REQUIRED','SERVICE STATES FIRST'];\n  if(type==='ch6_clockout_station_v25')return !s.accountabilityOne?['CONTRACTOR 14 SESSION','ACCOUNTABILITY REVIEW REQUIRED','CLOCK-OUT HELD']:s.clockedOut?['CONTRACTOR 14 • CLOCKED OUT','EXIT EVENT PENDING','PROCEED TO EMPLOYEE EXIT']:['ACCOUNTABILITY: 1','CONTRACTOR 14 ACTIVE','PHYSICAL CLOCK-OUT REQUIRED'];\n  return ['CLOSING CONTROL','STATE UNKNOWN'];",
    'clockout station lines',
)

p = one(
    p,
    "function refreshLastShiftRitualV25(s){for(const station of[s.rosterStation,s.keyStation,s.serviceStation,s.eliStation])refreshLastShiftRitualStationV25(s,station);}\nfunction lastShiftClosingStageV25(s){if(!s?.staffAcknowledged)return 0;if(!(s.keyCleared&&s.serviceCleared))return 1;if(!s.eliProcessed)return 2;if(!s.accountabilityOne)return 3;return 4;}",
    "function refreshLastShiftRitualV25(s){for(const station of[s.rosterStation,s.keyStation,s.serviceStation,s.eliStation,s.clockoutStation])refreshLastShiftRitualStationV25(s,station);}\nfunction lastShiftClosingStageV25(s){if(!s?.staffAcknowledged)return 0;if(!(s.keyCleared&&s.serviceCleared))return 1;if(!s.eliProcessed)return 2;if(!s.accountabilityOne)return 3;if(!s.clockedOut)return 4;if(!s.exitOpen)return 5;return 6;}",
    'closing stage expansion',
)

old_end = """  }else if(t==='ch6_eli_station_v25'){
    if(!(s.staffAcknowledged&&s.keyCleared&&s.serviceCleared)){audio.beep();UI.hint('Contractor 01 held • clear staff, key and service states first');return;}
    if(!(SAVE.story.evidence['LS-08']&&SAVE.story.evidence['LS-09']&&SAVE.story.completedEvents.ch5_eli_body)){audio.beep();UI.subtitle('ELI MERCER • SESSION 01 HELD','Processing requires Eli’s physical identification, LS-08 job recorder and LS-09 management override packet.','log',5600);return;}
    if(!s.eliProcessed){s.eliProcessed=true;s.accountabilityOne=true;SAVE.story.completedEvents.ch6_eli_processed=true;SAVE.story.completedEvents.ch6_accountability_one=true;SAVE.story.people.eli='cleared';SAVE.story.flags[STORY_DATA_V17.flags.contractor14Active]=true;save();audio.pickup();game.queueStory(.10,'intercom','PCAS','TEMP CONTRACTOR SESSION 01. ELI MERCER. DECEASED ON PROPERTY. EXIT EVENT IMPOSSIBLE. CONTRACTOR SESSION CLOSED BY ACCOUNTABILITY REVIEW.');game.storyV17.queueDialogue('ch6_accountability_one',3.0);game.queueStory(6.1,'radio','RENEE','Fourteen, Ward on dispatch. One. Not staff. Not Eli. The remaining account is the live contractor session. It is you.');}
  }
  if(s.keyCleared&&s.serviceCleared&&!s.servicePairAnnounced){s.servicePairAnnounced=true;SAVE.story.completedEvents.ch6_service_pair_cleared=true;save();game.queueStory(.35,'intercom','PCAS','KEY AND SERVICE DISCREPANCIES CLEARED. PERSONNEL EXCEPTION ROUTE: TEMP CONTRACTOR SESSION 01.');}
  refreshLastShiftRitualV25(s);
}
async function buildLastShiftV25(world){"""

new_end = """  }else if(t==='ch6_eli_station_v25'){
    if(!(s.staffAcknowledged&&s.keyCleared&&s.serviceCleared)){audio.beep();UI.hint('Contractor 01 held • clear staff, key and service states first');return;}
    if(!(SAVE.story.evidence['LS-08']&&SAVE.story.evidence['LS-09']&&SAVE.story.completedEvents.ch5_eli_body)){audio.beep();UI.subtitle('ELI MERCER • SESSION 01 HELD','Processing requires Eli’s physical identification, LS-08 job recorder and LS-09 management override packet.','log',5600);return;}
    if(!s.eliProcessed){s.eliProcessed=true;s.accountabilityOne=true;SAVE.story.completedEvents.ch6_eli_processed=true;SAVE.story.completedEvents.ch6_accountability_one=true;SAVE.story.people.eli='cleared';SAVE.story.flags[STORY_DATA_V17.flags.contractor14Active]=true;save();audio.pickup();game.queueStory(.10,'intercom','PCAS','TEMP CONTRACTOR SESSION 01. ELI MERCER. DECEASED ON PROPERTY. EXIT EVENT IMPOSSIBLE. CONTRACTOR SESSION CLOSED BY ACCOUNTABILITY REVIEW.');game.storyV17.queueDialogue('ch6_accountability_one',3.0);game.queueStory(6.1,'radio','RENEE','Fourteen, Ward on dispatch. One. Not staff. Not Eli. The remaining account is the live contractor session. It is you.');}
  }else if(t==='ch6_clockout_station_v25'){
    if(!s.accountabilityOne){audio.beep();UI.hint('Contractor 14 clock-out held • complete accountability review first');return;}
    if(!s.clockedOut){s.clockedOut=true;s.finalRecallActive=true;s.recallTimer=3.2;s.recallIndex=0;SAVE.story.completedEvents.ch6_clocked_out=true;save();audio.breaker();game.storyV17.queueDialogue('ch6_clockout',.10);game.storyV17.queueDialogue('ch6_radio_overlap',1.25);game.storyV17.queueDialogue('ch6_final_recall',2.55);game.attendant.awaken();UI.subtitle('TIME / ATTENDANCE','CONTRACTOR 14 CLOCK-OUT RECORDED • EXIT EVENT PENDING','log',5200);}
  }
  if(s.keyCleared&&s.serviceCleared&&!s.servicePairAnnounced){s.servicePairAnnounced=true;SAVE.story.completedEvents.ch6_service_pair_cleared=true;save();game.queueStory(.35,'intercom','PCAS','KEY AND SERVICE DISCREPANCIES CLEARED. PERSONNEL EXCEPTION ROUTE: TEMP CONTRACTOR SESSION 01.');}
  refreshLastShiftRitualV25(s);
}
function makeLastShiftExitGateV25(world,pos){
  const g=new THREE.Group();g.position.copy(pos);const steel=new THREE.MeshStandardMaterial({color:0x343a38,roughness:.66,metalness:.40}),lampMat=new THREE.MeshStandardMaterial({color:0x551b15,emissive:0xff3425,emissiveIntensity:.50,roughness:.35});const slab=addBox(g,new THREE.Vector3(0,1.22,0),new THREE.Vector3(.18,2.44,3.55),steel);const sign=new THREE.Mesh(new THREE.PlaneGeometry(2.45,.72),new THREE.MeshStandardMaterial({map:lastShiftPanelTextureV25('EMPLOYEE EXIT',['EXIT EVENT REQUIRED','CONTRACTOR 14'],'#d69a78'),emissive:0x362018,emissiveIntensity:.38,roughness:.62}));sign.position.set(-.101,1.58,0);sign.rotation.y=-Math.PI/2;g.add(sign);const lamp=new THREE.Mesh(new THREE.SphereGeometry(.07,12,10),lampMat);lamp.position.set(-.13,2.05,-1.35);g.add(lamp);world.root.add(g);const collider=world.addCollider(pos.x,pos.z,.34,3.72,{navBlock:true,owner:g,pad:.01});g.userData={type:'ch6_employee_exit_v25',label:'EMPLOYEE EXIT',slab,collider,lamp,open:false};world.interactables.push(g);return g;
}
function openLastShiftExitGateV25(game,g,silent=false){if(!g||g.userData.open)return;g.userData.open=true;g.userData.slab.position.y=3.35;if(g.userData.collider)g.userData.collider.disabled=true;if(g.userData.lamp?.material){g.userData.lamp.material.color.setHex(0x214b31);g.userData.lamp.material.emissive.setHex(0x66ff9a);g.userData.lamp.material.emissiveIntensity=1.25;}if(!silent){audio.door(true);game.emitSound(g.position.clone(),.42,'employee-exit-release');}}
function handleLastShiftExitV25(game,g){const s=game.ch6V25;if(!s)return;if(!s.clockedOut){audio.beep();UI.hint('EMPLOYEE EXIT HELD • Contractor 14 exit event is not armed');return;}if(!s.exitOpen){s.exitOpen=true;SAVE.story.completedEvents.ch6_exit_open=true;save();openLastShiftExitGateV25(game,g);game.queueStory(.15,'intercom','PCAS','EMPLOYEE EXIT RELEASED. CONTRACTOR 14 EXIT EVENT PENDING. RETURN TO ASSIGNED STATION.');s.recallTimer=Math.min(s.recallTimer,2.8);}else UI.hint('Employee exit open • cross the threshold');}
function finalRecallRouteV25(index){const routes=[{label:'PA CONTROL',pos:new THREE.Vector3(0,0,12)},{label:'KEY CONTROL',pos:new THREE.Vector3(-22,0,-12)},{label:'SERVICE STATE',pos:new THREE.Vector3(22,0,-12)},{label:'STAFF ACCOUNTABILITY',pos:new THREE.Vector3(-5.2,0,12)}];return routes[index%routes.length];}
function issueFinalRecallV25(game){const s=game.ch6V25;if(!s?.finalRecallActive)return null;const route=finalRecallRouteV25(s.recallIndex++),a=game.attendant;s.recallCount=(s.recallCount||0)+1;s.lastRecall=route.label;game.queueStory(.05,'intercom','PCAS',`CONTRACTOR FOURTEEN. REPORT TO ${route.label}. CLOSING CHECKLIST INCOMPLETE.`);a.awaken();let diverted=false;if(a.decoyUntil>game.time){diverted=true;}else{if(!a.root.visible)a.spawnHidden(game.controls.yaw.position)||a.spawnHidden(route.pos);if(a.root.visible){a.lastHeard.copy(route.pos);a.state='investigate';a.timer=7.4;a.repath=0;a.setPath(route.pos);}}const tele=window.__PINEWOOD_CH6_V25__;if(tele){tele.recallCount=s.recallCount;tele.recallTarget=route.label;tele.recallDivertedByDecoy=diverted;}return {label:route.label,diverted};}
function extinguishAttendantV25(attendant){if(!attendant)return;attendant.awake=false;attendant.state='dormant';attendant.path=[];attendant.timer=0;attendant.root?.traverse?.(o=>{const m=o.material;if(!m)return;for(const mat of Array.isArray(m)?m:[m]){if(mat?.emissive&&mat.emissive.getHex?.()===0xffffff){mat.emissive.setHex(0x000000);mat.emissiveIntensity=0;if(mat.color)mat.color.setHex(0x050505);}}});}
function completeLastShiftV25(game){const s=game.ch6V25;if(!s||s.completed||!s.clockedOut||!s.exitOpen)return false;s.completed=true;s.finalRecallActive=false;const trueEnding=storyLastShiftCompleteV17();const ending=trueEnding?STORY_DATA_V17.endings.true:STORY_DATA_V17.endings.standard;SAVE.story.completedEvents.ch6_complete=true;SAVE.story.completedEvents[trueEnding?'ch6_true_ending':'ch6_standard_ending']=true;if(trueEnding)SAVE.story.completedEvents.ch6_accountability_zero=true;else SAVE.story.completedEvents.contractor15_pending=true;SAVE.story.flags[STORY_DATA_V17.flags.contractor14Active]=false;SAVE.story.ending=ending;SAVE.story.chapterCheckpoint='complete';SAVE.unlockedChapter=Math.max(SAVE.unlockedChapter,5);SAVE.lastChapter=5;save();setLastShiftMemoryV25(game,false,'closing-release');if(trueEnding)extinguishAttendantV25(game.attendant);else{game.attendant.awake=false;game.attendant.state='dormant';game.attendant.path=[];game.attendant.timer=0;}game.won=true;game.running=false;game.modal=true;game.controls.unlock();const tele=window.__PINEWOOD_CH6_V25__;if(tele){tele.finalAccountability=true;tele.accountabilityZero=true;tele.contractor14Active=false;tele.ending=ending;tele.historicalResolution=!!trueEnding;tele.finalRecallActive=false;}game.updateMenu();$('chapterKicker').textContent=trueEnding?'TRUE ENDING':'END OF SHIFT';$('chapterTitle').textContent=trueEnding?'EVERYONE CLOCKED OUT':'PINEWOOD IS CLOSED';$('chapterCopy').textContent=trueEnding?'ACCOUNTABILITY: 0. The closing announcement begins normally, then stops before it can repeat. Lights fall dark behind you. The Attendant becomes still and its white eyes extinguish.\n\nOutside, Renee’s real voice returns clearly. Her console shows the Pinewood ticket archived against the original 1997 work order. No Contractor 15 appears.':'The attendance counter reaches zero long enough for the employee exit to release. Pinewood announces that the mall is closed, and the Attendant stops moving.\n\nOutside, Renee’s real voice returns and confirms the active ticket has closed. Later that night, her dispatch console receives another Pinewood emergency request. The new field reads CONTRACTOR 15.';$('chapterStartBtn').textContent='Return to Title';$('chapterStartBtn').onclick=()=>game.quit();$('chapterQuitBtn').style.display='none';UI.show('chapterScreen');return true;}
function chapter6TestStateV25(game){const s=game.ch6V25;return {staffAcknowledged:!!s.staffAcknowledged,keyCleared:!!s.keyCleared,serviceCleared:!!s.serviceCleared,eliProcessed:!!s.eliProcessed,accountabilityOne:!!s.accountabilityOne,clockedOut:!!s.clockedOut,finalRecallActive:!!s.finalRecallActive,recallCount:s.recallCount||0,lastRecall:s.lastRecall||null,exitOpen:!!s.exitOpen,completed:!!s.completed,ending:SAVE.story.ending||null,contractor14Active:!!SAVE.story.flags[STORY_DATA_V17.flags.contractor14Active],allEvidence:storyLastShiftCompleteV17()};}
function installChapter6TestApiV25(game,visualView){if(!visualView)return;const s=game.ch6V25;window.__PINEWOOD_CH6_TEST_V25__={prepare(mode='standard'){for(const id of STORY_DATA_V17.lastShiftIds){delete SAVE.story.evidence[id];delete SAVE.journal[id];}for(const k of Object.keys(SAVE.story.completedEvents||{}))if(k.startsWith('ch6_')||k==='contractor15_pending')delete SAVE.story.completedEvents[k];const ids=mode==='true'?STORY_DATA_V17.lastShiftIds:['LS-07','LS-08','LS-09'];for(const id of ids)SAVE.story.evidence[id]=true;SAVE.story.completedEvents.ch5_eli_body=true;SAVE.story.ending=null;SAVE.story.flags[STORY_DATA_V17.flags.contractor14Active]=true;Object.assign(s,{firstEchoSeen:true,staffAcknowledged:false,keyCleared:false,serviceCleared:false,servicePairAnnounced:false,eliProcessed:false,accountabilityOne:false,clockedOut:false,finalRecallActive:false,recallTimer:0,recallIndex:0,recallCount:0,lastRecall:null,exitOpen:false,completed:false});if(s.exitGate?.userData?.open){s.exitGate.userData.open=false;s.exitGate.userData.slab.position.y=1.22;if(s.exitGate.userData.collider)s.exitGate.userData.collider.disabled=false;}refreshLastShiftRitualV25(s);save();return chapter6TestStateV25(game);},interact(kind){const map={roster:s.rosterStation,key:s.keyStation,service:s.serviceStation,eli:s.eliStation,clockout:s.clockoutStation};const o=map[kind];if(!o)throw new Error('Unknown v25 test interaction '+kind);handleLastShiftRitualV25(game,o);return chapter6TestStateV25(game);},recall(){const r=issueFinalRecallV25(game);return {route:r,state:chapter6TestStateV25(game)};},openExit(){handleLastShiftExitV25(game,s.exitGate);return chapter6TestStateV25(game);},crossExit(){game.controls.yaw.position.set(28.1,1.70,-14);game.updateLastShiftV25(.016);return chapter6TestStateV25(game);},state(){return chapter6TestStateV25(game);}};}
async function buildLastShiftV25(world){"""
p = one(p, old_end, new_end, 'finale helper insertion')

old_state = """  const s=GAME.ch6V25={cycle:0,memoryActive:false,memoryApplied:false,forcedMemory,firstEchoSeen:!!SAVE.story.completedEvents.ch6_first_memory,staffAcknowledged:!!SAVE.story.completedEvents.ch6_staff_acknowledged,keyCleared:!!SAVE.story.completedEvents.ch6_key_cleared,serviceCleared:!!SAVE.story.completedEvents.ch6_service_cleared,servicePairAnnounced:!!SAVE.story.completedEvents.ch6_service_pair_cleared,eliProcessed:!!SAVE.story.completedEvents.ch6_eli_processed,accountabilityOne:!!SAVE.story.completedEvents.ch6_accountability_one,presentGroup:new THREE.Group(),memoryGroup:new THREE.Group(),echoRoot:null,presentLight:null,presentTaskLight:null,memoryLight:null,memoryFill:null,rosterStation:null,keyStation:null,serviceStation:null,eliStation:null};
  s.presentGroup.userData.chapter6StateV25='present';s.memoryGroup.userData.chapter6StateV25='memory-1997';world.root.add(s.presentGroup);world.root.add(s.memoryGroup);
  window.__PINEWOOD_CH6_V25__={version:25,lastShift:true,memoryOverlay:true,locationSpecific:true,staffSilhouettes:true,closingSequence:true,finalAccountability:false,sceneBuilt:false,memoryActive:false,memoryTransitions:0,lastTransition:'build',staffAcknowledged:!!s.staffAcknowledged,keyCleared:!!s.keyCleared,serviceCleared:!!s.serviceCleared,eliProcessed:!!s.eliProcessed,accountabilityOne:!!s.accountabilityOne,closingStage:lastShiftClosingStageV25(s)};"""
new_state = """  const s=GAME.ch6V25={cycle:0,memoryActive:false,memoryApplied:false,forcedMemory,firstEchoSeen:!!SAVE.story.completedEvents.ch6_first_memory,staffAcknowledged:!!SAVE.story.completedEvents.ch6_staff_acknowledged,keyCleared:!!SAVE.story.completedEvents.ch6_key_cleared,serviceCleared:!!SAVE.story.completedEvents.ch6_service_cleared,servicePairAnnounced:!!SAVE.story.completedEvents.ch6_service_pair_cleared,eliProcessed:!!SAVE.story.completedEvents.ch6_eli_processed,accountabilityOne:!!SAVE.story.completedEvents.ch6_accountability_one,clockedOut:!!SAVE.story.completedEvents.ch6_clocked_out,finalRecallActive:!!SAVE.story.completedEvents.ch6_clocked_out&&!SAVE.story.completedEvents.ch6_complete,recallTimer:2.8,recallIndex:0,recallCount:0,lastRecall:null,exitOpen:!!SAVE.story.completedEvents.ch6_exit_open,completed:!!SAVE.story.completedEvents.ch6_complete,presentGroup:new THREE.Group(),memoryGroup:new THREE.Group(),echoRoot:null,presentLight:null,presentTaskLight:null,memoryLight:null,memoryFill:null,rosterStation:null,keyStation:null,serviceStation:null,eliStation:null,clockoutStation:null,exitGate:null};
  if(visualView==='last-shift-clockout'||visualView==='last-shift-exit'){Object.assign(s,{firstEchoSeen:true,staffAcknowledged:true,keyCleared:true,serviceCleared:true,eliProcessed:true,accountabilityOne:true});if(visualView==='last-shift-exit')Object.assign(s,{clockedOut:true,finalRecallActive:true,exitOpen:true});}
  s.presentGroup.userData.chapter6StateV25='present';s.memoryGroup.userData.chapter6StateV25='memory-1997';world.root.add(s.presentGroup);world.root.add(s.memoryGroup);
  window.__PINEWOOD_CH6_V25__={version:25,lastShift:true,memoryOverlay:true,locationSpecific:true,staffSilhouettes:true,closingSequence:true,finalAccountability:true,sceneBuilt:false,memoryActive:false,memoryTransitions:0,lastTransition:'build',staffAcknowledged:!!s.staffAcknowledged,keyCleared:!!s.keyCleared,serviceCleared:!!s.serviceCleared,eliProcessed:!!s.eliProcessed,accountabilityOne:!!s.accountabilityOne,clockedOut:!!s.clockedOut,finalRecallActive:!!s.finalRecallActive,recallCount:s.recallCount,recallTarget:null,exitOpen:!!s.exitOpen,accountabilityZero:false,ending:SAVE.story.ending||null,closingStage:lastShiftClosingStageV25(s)};"""
p = one(p, old_state, new_state, 'finale state')

old_stations = """  s.rosterStation=makeLastShiftRitualStationV25(world,new THREE.Vector3(-5.2,.02,12.5),Math.PI,'ch6_roster_station_v25','STAFF ACCOUNTABILITY','#9fc5a9');s.eliStation=makeLastShiftRitualStationV25(world,new THREE.Vector3(5.2,.02,12.5),Math.PI,'ch6_eli_station_v25','CONTRACTOR 01','#d2b374');s.keyStation=makeLastShiftRitualStationV25(world,new THREE.Vector3(-22,.02,-12),0,'ch6_key_station_v25','KEY CONTROL','#a7b9aa');s.serviceStation=makeLastShiftRitualStationV25(world,new THREE.Vector3(22,.02,-12),0,'ch6_service_station_v25','SERVICE STATE','#a7b9aa');refreshLastShiftRitualV25(s);
  for(const[x,z,c,tag]of[[-5.2,12.1,0xaac4b7,'roster-control'],[5.2,12.1,0xd5b87d,'eli-control'],[-22,-11.5,0x9eb6aa,'key-control'],[22,-11.5,0x9eb6aa,'service-control']]){const l=new THREE.PointLight(c,1.18,5.8,2);l.position.set(x,2.05,z);l.userData.chapter6LightV25=tag;world.root.add(l);}"""
new_stations = """  s.rosterStation=makeLastShiftRitualStationV25(world,new THREE.Vector3(-5.2,.02,12.5),Math.PI,'ch6_roster_station_v25','STAFF ACCOUNTABILITY','#9fc5a9');s.eliStation=makeLastShiftRitualStationV25(world,new THREE.Vector3(5.2,.02,12.5),Math.PI,'ch6_eli_station_v25','CONTRACTOR 01','#d2b374');s.keyStation=makeLastShiftRitualStationV25(world,new THREE.Vector3(-22,.02,-12),0,'ch6_key_station_v25','KEY CONTROL','#a7b9aa');s.serviceStation=makeLastShiftRitualStationV25(world,new THREE.Vector3(22,.02,-12),0,'ch6_service_station_v25','SERVICE STATE','#a7b9aa');s.clockoutStation=makeLastShiftRitualStationV25(world,new THREE.Vector3(-24.5,.02,-14),Math.PI/2,'ch6_clockout_station_v25','CONTRACTOR 14','#d99a7d');s.exitGate=makeLastShiftExitGateV25(world,new THREE.Vector3(27.2,0,-14));if(s.exitOpen)openLastShiftExitGateV25(GAME,s.exitGate,true);refreshLastShiftRitualV25(s);
  for(const[x,z,c,tag]of[[-5.2,12.1,0xaac4b7,'roster-control'],[5.2,12.1,0xd5b87d,'eli-control'],[-22,-11.5,0x9eb6aa,'key-control'],[22,-11.5,0x9eb6aa,'service-control'],[-24.0,-14,0xd29a82,'contractor14-clock'],[26.2,-14,0x86c19c,'employee-exit']]){const l=new THREE.PointLight(c,1.18,5.8,2);l.position.set(x,2.05,z);l.userData.chapter6LightV25=tag;world.root.add(l);}"""
p = one(p, old_stations, new_stations, 'finale stations')

p = one(
    p,
    "  setLastShiftMemoryV25(GAME,forcedMemory===null?true:forcedMemory,forcedMemory===null?'chapter-entry':'visual-test');\n  window.__PINEWOOD_CH6_V25__.sceneBuilt=true;",
    "  setLastShiftMemoryV25(GAME,forcedMemory===null?true:forcedMemory,forcedMemory===null?'chapter-entry':'visual-test');\n  window.__PINEWOOD_CH6_V25__.sceneBuilt=true;installChapter6TestApiV25(GAME,visualView);",
    'test API install',
)

p = one(
    p,
    "else if(t==='ch6_eli_station_v25')UI.hint('E  Process Eli Mercer • Contractor 01');else if(t==='note'||t==='journal'||t==='tape')UI.hint('E  Recover '+o.userData.label);",
    "else if(t==='ch6_eli_station_v25')UI.hint('E  Process Eli Mercer • Contractor 01');else if(t==='ch6_clockout_station_v25')UI.hint(this.ch6V25?.clockedOut?'Contractor 14 clock-out recorded • reach employee exit':'E  Clock out Contractor 14');else if(t==='ch6_employee_exit_v25')UI.hint(!this.ch6V25?.clockedOut?'EMPLOYEE EXIT HELD • clock-out required':o.userData.open?'Employee exit open • cross the threshold':'E  Release employee exit');else if(t==='note'||t==='journal'||t==='tape')UI.hint('E  Recover '+o.userData.label);",
    'finale interaction hints',
)

p = one(
    p,
    "}else if(t==='ch6_roster_station_v25'||t==='ch6_key_station_v25'||t==='ch6_service_station_v25'||t==='ch6_eli_station_v25'){handleLastShiftRitualV25(this,o);\n    }else if(t==='note'||t==='journal'||t==='tape'){",
    "}else if(t==='ch6_roster_station_v25'||t==='ch6_key_station_v25'||t==='ch6_service_station_v25'||t==='ch6_eli_station_v25'||t==='ch6_clockout_station_v25'){handleLastShiftRitualV25(this,o);\n    }else if(t==='ch6_employee_exit_v25'){handleLastShiftExitV25(this,o);\n    }else if(t==='note'||t==='journal'||t==='tape'){",
    'finale interaction handlers',
)

old_methods = """  updateLastShiftV25(dt){if(this.levelIndex!==5||!this.ch6V25)return;const s=this.ch6V25;s.cycle+=dt;let active=s.forcedMemory;if(active===null){const phase=s.cycle%12;active=phase<4.2;}setLastShiftMemoryV25(this,active,active?'pcas-reconstruction':'present-collapse');if(s.echoRoot?.userData?.actionArm&&s.memoryActive){const p=s.echoRoot.userData.phase+s.cycle*1.7;s.echoRoot.userData.actionArm.rotation.z=-.22+Math.sin(p)*.18;}if(!s.firstEchoSeen&&s.cycle>4.4&&s.forcedMemory===null){s.firstEchoSeen=true;SAVE.story.completedEvents.ch6_first_memory=true;save();this.queueStory(.15,'radio','RENEE','Fourteen, Ward on dispatch. I lost your telemetry for four seconds. The room on my feed never changed. Whatever you just saw was Pinewood replaying a closing state. Use it as evidence, not directions.');}const t=window.__PINEWOOD_CH6_V25__;if(t){t.firstEchoSeen=!!s.firstEchoSeen;t.staffAcknowledged=!!s.staffAcknowledged;t.keyCleared=!!s.keyCleared;t.serviceCleared=!!s.serviceCleared;t.eliProcessed=!!s.eliProcessed;t.accountabilityOne=!!s.accountabilityOne;t.closingStage=lastShiftClosingStageV25(s);t.cycle=Number(s.cycle.toFixed(2));}}
  chapter6ObjectiveV25(){const s=this.ch6V25;if(!s)return'Enter PA / accountability control';if(!s.firstEchoSeen)return'Observe the first 1997 closing-memory reconstruction';if(!s.staffAcknowledged)return'Acknowledge seven confirmed staff departures at Staff Accountability';if(!(s.keyCleared&&s.serviceCleared))return'Clear Key Control and Service State discrepancies';if(!s.eliProcessed)return'Process Eli Mercer • Contractor 01 using LS-08 and LS-09';if(!s.accountabilityOne)return'Read the remaining accountability state';return'ACCOUNTABILITY: 1 • identify the remaining active contractor';}"""
new_methods = """  updateLastShiftV25(dt){if(this.levelIndex!==5||!this.ch6V25)return;const s=this.ch6V25;s.cycle+=dt;let active=s.forcedMemory;if(active===null){const span=s.finalRecallActive?6.4:12,shown=s.finalRecallActive?2.15:4.2,phase=s.cycle%span;active=phase<shown;}setLastShiftMemoryV25(this,active,active?'pcas-reconstruction':'present-collapse');if(s.echoRoot?.userData?.actionArm&&s.memoryActive){const p=s.echoRoot.userData.phase+s.cycle*1.7;s.echoRoot.userData.actionArm.rotation.z=-.22+Math.sin(p)*.18;}if(!s.firstEchoSeen&&s.cycle>4.4&&s.forcedMemory===null){s.firstEchoSeen=true;SAVE.story.completedEvents.ch6_first_memory=true;save();this.queueStory(.15,'radio','RENEE','Fourteen, Ward on dispatch. I lost your telemetry for four seconds. The room on my feed never changed. Whatever you just saw was Pinewood replaying a closing state. Use it as evidence, not directions.');}if(s.finalRecallActive&&!s.completed){s.recallTimer-=dt;if(s.recallTimer<=0){issueFinalRecallV25(this);s.recallTimer=7.2;}const pp=this.controls.yaw.position;if(s.exitOpen&&pp.x>27.45&&pp.z>-18.6&&pp.z<-7.0)completeLastShiftV25(this);}const t=window.__PINEWOOD_CH6_V25__;if(t){t.firstEchoSeen=!!s.firstEchoSeen;t.staffAcknowledged=!!s.staffAcknowledged;t.keyCleared=!!s.keyCleared;t.serviceCleared=!!s.serviceCleared;t.eliProcessed=!!s.eliProcessed;t.accountabilityOne=!!s.accountabilityOne;t.clockedOut=!!s.clockedOut;t.finalRecallActive=!!s.finalRecallActive;t.recallCount=s.recallCount||0;t.recallTarget=s.lastRecall||null;t.exitOpen=!!s.exitOpen;t.contractor14Active=!!SAVE.story.flags[STORY_DATA_V17.flags.contractor14Active];t.ending=SAVE.story.ending||null;t.closingStage=lastShiftClosingStageV25(s);t.cycle=Number(s.cycle.toFixed(2));}}
  chapter6ObjectiveV25(){const s=this.ch6V25;if(!s)return'Enter PA / accountability control';if(!s.firstEchoSeen)return'Observe the first 1997 closing-memory reconstruction';if(!s.staffAcknowledged)return'Acknowledge seven confirmed staff departures at Staff Accountability';if(!(s.keyCleared&&s.serviceCleared))return'Clear Key Control and Service State discrepancies';if(!s.eliProcessed)return'Process Eli Mercer • Contractor 01 using LS-08 and LS-09';if(!s.accountabilityOne)return'Read the remaining accountability state';if(!s.clockedOut)return'Cross to Time / Attendance • clock out Contractor 14';if(!s.exitOpen)return'Reach the east Employee Exit • release the door';return'Exit Pinewood before the next Contractor 14 recall';}"""
p = one(p, old_methods, new_methods, 'finale update and objectives')

p = one(
    p,
    "      'last-shift-eli-control':{chapter:5,p:[5.2,1.65,9.4],yaw:Math.PI,pitch:-.06}",
    "      'last-shift-eli-control':{chapter:5,p:[5.2,1.65,9.4],yaw:Math.PI,pitch:-.06},\\n      'last-shift-clockout':{chapter:5,p:[-20.5,1.65,-14],yaw:Math.PI/2,pitch:-.055},\\n      'last-shift-exit':{chapter:5,p:[23.4,1.65,-14],yaw:-Math.PI/2,pitch:-.045}",
    'finale visual views',
)

p = one(
    p,
    '"finalAccountability:false"',
    '"finalAccountability:true"',
    'final accountability self check',
)

# Expand the v25 self-check list immediately before the closing bracket.
p = one(
    p,
    "\"'last-shift-eli-control':{chapter:5\"]){if(!source.includes(marker))fail('required v25 marker missing: '+marker);}",
    "\"'last-shift-eli-control':{chapter:5\",\"ch6_clockout_station_v25\",\"ch6_employee_exit_v25\",\"ch6_clocked_out\",\"a.state='investigate'\",\"storyLastShiftCompleteV17()\",\"STORY_DATA_V17.endings.true\",\"STORY_DATA_V17.endings.standard\",\"'last-shift-clockout':{chapter:5\",\"'last-shift-exit':{chapter:5\"]){if(!source.includes(marker))fail('required v25 marker missing: '+marker);}",
    'finale self-check expansion',
)

patch_path.write_text(p)

dpath = Path('story/dialogue.js')
d = dpath.read_text()
old_dialogue = """  ch6_accountability_one:{id:'ch6_accountability_one',speaker:'PCAS',medium:'terminal',text:'ACCOUNTABILITY: 1. CONTRACTOR 14 SESSION ACTIVE. EXIT EVENT REQUIRED.'},
  ch6_final_recall:{id:'ch6_final_recall',speaker:'PCAS',medium:'intercom',text:'Contractor Fourteen, return to your assigned station. Closing checklist incomplete.'}
};"""
new_dialogue = """  ch6_accountability_one:{id:'ch6_accountability_one',speaker:'PCAS',medium:'terminal',text:'ACCOUNTABILITY: 1. CONTRACTOR 14 SESSION ACTIVE. EXIT EVENT REQUIRED.'},
  ch6_clockout:{id:'ch6_clockout',speaker:'PCAS',medium:'terminal',text:'CONTRACTOR 14 CLOCK-OUT RECORDED. EXIT EVENT PENDING. PROCEED TO EMPLOYEE EXIT.'},
  ch6_radio_overlap:{id:'ch6_radio_overlap',speaker:'RENEE / UNKNOWN',medium:'radio',text:'Fourteen, Ward on dispatch. Employee exit is east— Fourteen, Ward on dispatch. Return to assigned station— east exit, physical signs only— return to assigned station.'},
  ch6_final_recall:{id:'ch6_final_recall',speaker:'PCAS',medium:'intercom',text:'Contractor Fourteen, return to your assigned station. Closing checklist incomplete.'},
  ch6_accountability_zero:{id:'ch6_accountability_zero',speaker:'PCAS',medium:'terminal',text:'ACCOUNTABILITY: 0. ALL STAFF ACCOUNTED FOR. CLOSING RELEASE AUTHORIZED.'}
};"""
d = one(d, old_dialogue, new_dialogue, 'finale structured dialogue')
dpath.write_text(d)

print('Chapter 6 finale patch staged successfully.')
